Artisan-Lab/RAPx

- rap/src/analysis/core/dataflow.rs
- rap/src/analysis/core/dataflow/debug.rs
- rap/src/analysis/core/dataflow/graph.rs
- rap/src/analysis/utils.rs
- rap/src/analysis/utils/def_path.rs
- add a function in `utils` to convert a def path(String) into its def id
- the code refers to that of clippy
- fix bugs in graph building
- the former version view a `Place` as a local, while more than one assignments can take place on a `Place`, thus we should identify them. this pr supports **a part of** variants of `Place`, and add virtual node markers in the graph
- correspondingly implement `to_dot_graph` functions
- refactor the code to extact the debug code together
> fix bugs of graph building & optimize debug code

- rap/src/analysis/core/dataflow.rs
The previous pull request missed a statement to introduce the impls into the code.
> fix: compiler error caused by missing of a statement

- .github/workflows/release.yml
- README.md
- rap/rust-toolchain.toml
This PR includes:
* stripping target triple from channel field (refer to https://rust-lang.github.io/rustup/overrides.html#channel )
* fixing a typo in component name
* updating actions/setup-python from v3 to v5
* updating README in usage with toolchain installation and override shorthand syntax
> Fix toolchain and CI, and update README

- rap/src/analysis/utils/def_path.rs
- rap/src/lib.rs
Now functions in `def_path.rs` can work properly.
Note that the newest clippy code matches current rustc with different API definitions from that of 2024-06-30. Therefore, I use the corresponding clippy code in a history commit nearby Jun 30.
> update def_path to match the new rust version

- rap/Cargo.toml
- rap/src/bin/cargo-rap.rs
- rap/src/bin/rap.rs
- rap/src/utils/log.rs
As discussed [here](https://github.com/Artisan-Lab/RAP/issues/53#issuecomment-2414036262), `RAP_LOG` is supported in this PR to dynamically set log level.
If RAP_LOG is not set, the default level is info as before.
I also remove -debug option because it'd be better to expose single way via RAP_LOG to set up the log level. The option now is equivalent to `RAP_LOG=DEBUG`.
The value on RAP_LOG is case-insensitive, which is defined in [LevelFilter::from_str](https://docs.rs/log/0.4.22/src/log/lib.rs.html#629-635).
`Verbosity` is also removed, because there is no reason to use it now.
Some tests:
* `cargo +nightly-2024-06-30 rap -F` and `RAP_LOG=WARN cargo +nightly-2024-06-30 rap -F`
* `RAP_LOG=DEBUG cargo +nightly-2024-06-30 rap -F`
> feat: support `RAP_LOG` environment variable; remove `-debug` option 

- rap/src/utils/log.rs
This PR changes log.rs to:
- replace "RAP_FRONT" with "RAP". Since RAP no longer has the concepts of "frontend" and "backend", there is no means to use "RAP_FRONT".
- use ISO 8601 timestamp for all logging. This facilitates the debugging and profiling of RAP. 
Below is an example of the new logging format:
> feat: replace "RAP_FRONT" with "RAP"; use ISO 8601 timestamp in log

- rap/src/analysis/core/alias.rs
- rap/src/analysis/core/alias/mop.rs
- rap/src/analysis/core/alias/mop/alias.rs
- rap/src/analysis/core/alias/mop/graph.rs
- rap/src/analysis/core/alias/mop/mop.rs
- rap/src/analysis/core/alias/mop/types.rs
- rap/src/analysis/safedrop/alias.rs
- rap/src/utils/log.rs
This PR includes:
- feat: remove the millisecond format in the log. Now the date format in logging is %H:%M:%S".
- feat: change the log level from INFO to DEBUG in the alias module. Remove redundant logging messages.
- feat: use std::collections::HashSet to store RetAlias so we can prevent duplicate aliases from the result. 
- refactor: fix most of the cargo clippy warnings in the alias module.
> Refactor alias module; Use HashSet to store RetAlias

- rap/src/analysis/senryx/visitor.rs
This pr removes the reserved _handle_projection_ interface and reuses the _projection_ method in safedrop.
Senryx will continue to reuse safedrop's alias analysis and other basic modules.
> Modify Projection in Senryx

- rap/src/analysis/senryx.rs
- rap/src/analysis/senryx/contracts/abstract_state.rs
- rap/src/analysis/senryx/contracts/checker.rs
- rap/src/analysis/senryx/matcher.rs
- rap/src/analysis/senryx/visitor.rs
- rap/src/lib.rs
- tests/senryx_tests/slice_from_raw_parts/src/main.rs
This pr:
1. Add the basic align check module, which tracks the abstract state based on the rvalue of the pointer type and checks for the presence of small to big casts
2. Use CVE's classic align issue as a test case, now you can:
`cd tests/senryx_tests/slice_from_raw_parts/`
Then run `cargo rap -senryx` to get an initial version of the output.
Other unsafe apis and program status are tracked and developed based on this demo in the future.
> Add a simple alignment check in senryx

- rap/src/bin/cargo-rap/args.rs
- rap/src/bin/cargo-rap/main.rs
so far, the following usages on cargo-rap are tested:
```bash
export RAP_LOG=warn
cargo rap -F -M -- -p ws-rap-checks-this1
cargo rap -F -M -- -p ws-rap-checks-this2
cargo rap -F -M -- --workspace
cargo rap -F -M -- -p ws-rap-checks-this_with-feature-gated -F rap
cargo rap -F -M -- -p ws-rap-checks-this_with-build-script
cargo rap -F -M -- -p ws-rap-checks-test-and-example --examples --tests
cd crates/ws-rap-checks-test-and-example
cargo rap -F -M -- --example ex1
cargo rap -F -M -- --examples
cargo rap -F -M -- --tests
cargo rap -F -M -- --examples --tests
```
see https://github.com/os-checker/os-checker-test-suite/tree/main/workspace2
> fix: replace is_crate_type_lib by filter_crate_type to support extra crate-types

- rap/Cargo.lock
- rap/src/bin/cargo-rap/args.rs
- rap/src/bin/cargo-rap/cargo_check.rs
- rap/src/bin/cargo-rap/main.rs
Checking proc macro crates will raise cc errors. So directly pass it to rustc instead of to rap.
For tokio:
before:
after:
> fix: ignore proc-macro crates in rap

- .github/workflows/release.yml
- README.md
- rap/Cargo.lock
- rap/Cargo.toml
- rap/src/bin/cargo-rap/args.rs
- rap/src/bin/cargo-rap/cargo_check.rs
- rap/src/bin/cargo-rap/cargo_check/workspace.rs
- rap/src/bin/cargo-rap/help.rs
- rap/src/bin/cargo-rap/main.rs
This PR introduce RAP_CLEAN and RAP_CLEAN environment variables:
Environment variables (Values are case insensitive):
| var             | default when absent | one of these values | description                  |
|-----------------|---------------------|---------------------|------------------------------|
| `RAP_CLEAN`     | true                | ture, false         | run cargo clean before check |
| `RAP_RECURSIVE` | none                | none, shallow, deep | scope of packages to check   |
For `RAP_RECURSIVE`:
* none: check for current folder
* shallow: check for current workpace members
* deep: check for all workspaces from current folder
NOTE: for shallow or deep, rap will enter each member folder to do the check.
---
Output of this PR: …
> feaf: introduce `RAP_RECURSIVE` to check packages recursively and `RAP_CLEAN` to run cargo clean before check

- rap/src/analysis/senryx.rs
- rap/src/analysis/senryx/contracts/checker.rs
- rap/src/analysis/senryx/matcher.rs
- rap/src/analysis/senryx/visitor.rs
- rap/src/analysis/utils/show_mir.rs
This pr modifies the previous senryx checking result output format, and make the output information dependent on the path. 
This means that the path to triggering a bug can be given based on the output information in the future.
> Modify analysis result format in senryx

- Dockerfile
- install.sh
The `Dockerfile` is not for current version of RAP.
The `install.sh` does not install the Rust toolchain before install the RAP.
> Fix Dockerfile

- rap/src/analysis/core/dataflow/debug.rs
- rap/src/analysis/core/dataflow/graph.rs
- rap/src/analysis/opt.rs
- rap/src/analysis/opt/memory_cloning.rs
- rap/src/analysis/opt/memory_cloning/hash_key_cloning.rs
- tests/hash_key_cloning/Cargo.toml
- tests/hash_key_cloning/src/lib.rs
Feats:
- Now closure functions can be represented well in dataflow graph
- Add sequence number on edges to differentiate between assignment operations [a local may be assigned for several times]
- Add hash key cloning detection
Notes:
Also Found the method to bridge HIR and MIR:
- We can use `Span` as a bridge between HIR and MIR. The `Expr` in HIR has the span field while the dataflow graph also marks span for each node.
- Now I am using a dummy method of plainly searching. Maybe a map from span to node can help boost the performance.
Warnings:
- HIR APIs also change a lot in the update nightly Rust. Thus we may encounter more problems in the next upgrading.
> feat: support closure and sequence number in dataflow, add hash key cloning detection

- rap/src/analysis/core/dataflow/debug.rs
- rap/src/analysis/core/dataflow/graph.rs
- rap/src/analysis/opt/checking/bounds_checking/bounds_len.rs
- rap/src/analysis/opt/memory_cloning/hash_key_cloning.rs
- Remove `ConstEdge` and add `NodeOp::Const`. Now `GraphEdge` is a `struct` instead of an `enum`.
- Previously, the node operator (a closure) of DFS catched graph outside. Now we explicitly pass a graph as its parameter. Correspondingly, the edge operator also takes a graph and an `EdgeIdx` (instead of EdgeOp) as parameters. So now we have more flexibility to read data whether from nodes or edges during DFS.
> Change API definition in dataflow graph

- rap/src/analysis/opt.rs
- rap/src/analysis/opt/memory_cloning.rs
- rap/src/analysis/opt/memory_cloning/used_as_immutable.rs
- detect `cloned value used as immutable`
- temporarily remove detection of `hash key cloning` in the main function because the exception is covered
> feat: cloned value used as immutable

- tests/batch.sh
exit if rap errs even if WARN is got
> fix: detect ERROR report in batch.sh

- rap/src/analysis/opt/checking/bounds_checking/bounds_len.rs
- rap/src/analysis/opt/checking/bounds_checking/bounds_loop_push.rs
- rap/src/analysis/opt/memory_cloning/hash_key_cloning.rs
- rap/src/analysis/opt/memory_cloning/used_as_immutable.rs
- rap/src/analysis/safedrop/bug_records.rs
- rap/src/analysis/safedrop/check_bugs.rs
- rap/src/utils/log.rs
Use annotate_anippet to rewrite the bug report of safedrop.
Now safedrop still `reports` spans from non-local source code. Thus I add a condition which filters out the special cases.
During the debugging, I find that `relative_pos_range` API may have overflow problems. Therefore, an `unsafe` keyword is added in this function's declaration.
> rewrite bug report of safedrop

- rapx/src/analysis/core/dataflow/debug.rs
- rapx/src/analysis/core/dataflow/graph.rs
- rapx/src/analysis/opt.rs
- rapx/src/analysis/opt/checking/bounds_checking.rs
- rapx/src/analysis/opt/checking/bounds_checking/bounds_len.rs
- rapx/src/analysis/opt/checking/bounds_checking/bounds_loop_push.rs
- rapx/src/analysis/opt/memory_cloning/hash_key_cloning.rs
- rapx/src/analysis/opt/memory_cloning/used_as_immutable.rs
- Some match arms in datagraph have been implemented now to avoid panic
- **Change the basic field op in the GraphNode.**
- Previously, our datagraph was build upon a hypothesis that every `Local` in MIR should be assigned for once and only once.
- While actually we found that a Local can be assigned for multiple times. Thus I added the `seq` marker in edges to differentiate between edges.
- However, the nodeop also needs to save the previous one and keep every record available.
- In this PR, the `op` field is replaced by `ops` which is a `Vec<NodeOp>` and corresponding codes are also revised.
> Fix: todos in datagraph and nodeop replacement bug

- rapx/Cargo.toml
This patch is for better install experience for z3
for most z3 compile like Mac M1-M4 and arm system, its hard for new user to install z3.h in their env,
This patch use static-link to easy user install.
More info can check: https://github.com/prove-rs/z3.rs/issues/224
#2 and #58
> fix: better install user experience for z3

- rapx/Cargo.toml
- rapx/src/analysis/senryx/visitor.rs
- rapx/src/analysis/unsafety_isolation.rs
- rapx/src/analysis/unsafety_isolation/data/std_sps.json
- rapx/src/analysis/unsafety_isolation/draw_dot.rs
- rapx/src/analysis/unsafety_isolation/generate_dot.rs
- rapx/src/analysis/unsafety_isolation/std_unsafety_isolation.rs
- rapx/src/bin/cargo-rapx/args.rs
This PR adds the functionality to detect the safety properties (SP) of unsafe APIs in the standard library's core and alloc modules. Currently, it provides a basic comparison of whether the caller and callee have the same SP. More in-depth analysis will be added in the future.
Usage:
1. Create a new `helloworld` project.
2. Navigate to the `helloworld` project directory and run:
```
cargo rapx -upg -- -Z build-std --target x86_64-unknown-linux-gnu > /your/output/log/path/result.log 2>&1
(Replace /your/output/log/path with your desired output directory.)
```
This will output APIs where the caller and callee have different SPs.
> add core&alloc sp check

- rapx/src/utils/log.rs
> fix: check vaild frist when relative_pos_range close #94

- rapx/src/analysis/senryx.rs
- rapx/src/analysis/unsafety_isolation.rs
- rapx/src/analysis/unsafety_isolation/data/std_sps.json
- rapx/src/analysis/unsafety_isolation/std_unsafety_isolation.rs
- tests/support/safety_check/audit_case1/Cargo.toml
- tests/support/safety_check/audit_case1/src/main.rs
Uphold safety of method to its unsafe constructor simply and add a test case in this situation (see RAP/tests/support/safety_check/audit_case1) .
> Uphold safety to unsafe constructor

- rapx/Cargo.toml
- rapx/src/analysis/senryx.rs
- rapx/src/analysis/senryx/contracts/abstract_state.rs
- rapx/src/analysis/senryx/contracts/checker.rs
- rapx/src/analysis/senryx/contracts/contract.rs
- rapx/src/analysis/senryx/contracts/state_lattice.rs
- rapx/src/analysis/senryx/generic_check.rs
- rapx/src/analysis/senryx/inter_record.rs
- rapx/src/analysis/senryx/matcher.rs
- rapx/src/analysis/senryx/visitor.rs
- rapx/src/analysis/unsafety_isolation.rs
- rapx/src/analysis/unsafety_isolation/data/std_sps.json
- rapx/src/analysis/unsafety_isolation/generate_dot.rs
- rapx/src/analysis/unsafety_isolation/std_unsafety_isolation.rs
- rapx/src/analysis/utils.rs
- rapx/src/analysis/utils/fn_info.rs
- rapx/src/lib.rs
- tests/support/safety_check/slice_from_raw_parts/Cargo.toml
- tests/support/safety_check/slice_from_raw_parts/src/main.rs
Now the `senryx` is updated to support alignment analysis of generic type.
Specifically, in the function with generic params, `senryx` will extract all the possible types that satisfy the trait bounds. Then when the unsafe function requiring `arg` to be aligned is called, alignment check will be performed to verify whether all the satisfied typed can pass the align contract.
Test case:
```
cd tests/support/safety_check/slice_from_raw_parts
cargo rapx -A
```
The test case shows two scenarios that one contains generic params while another doesn't.
> Feat: support alignment analysis of generic type

- rapx/src/analysis/api_dep/mod.rs
- rapx/src/analysis/api_dep/visitor.rs
Addressed excessive lint warnings by applying the `#[allow(unused)]` attribute to modules under development.
> [api-dep] fix: lint warnings

- rapx/src/analysis/opt.rs
- rapx/src/analysis/opt/checking/bounds_checking/bounds_loop_push.rs
- rapx/src/analysis/opt/data_collection/slice_contains.rs
- rapx/src/analysis/opt/iterator.rs
- rapx/src/analysis/opt/iterator/next_iterator.rs
- tests/support/opt/iter_chunk/Cargo.toml
- tests/support/opt/iter_chunk/src/lib.rs
- tests/support/opt/slice_contains/Cargo.toml
- tests/support/opt/slice_contains/src/lib.rs
- tests/support/opt/vec_contains/src/lib.rs
- Detect whether a function uses both `next` and `chain` method of `iterator` which might be optimized by using `chunk` iterators.
- Reduce false positives by filtering in bounds checks
> Feat: add next iterator checks

- rapx/src/analysis/opt/memory_cloning/hash_key_cloning.rs
Add hashmap related function and add `with_capacity` detection (the original version only detects `new`)
> support hashmap in hash key cloning

- rapx/src/analysis/core/dataflow.rs
- rapx/src/analysis/core/dataflow/graph.rs
- rapx/src/analysis/opt.rs
- rapx/src/analysis/opt/checking/bounds_checking/bounds_len.rs
- rapx/src/analysis/opt/checking/bounds_checking/bounds_loop_push.rs
Now RAPx -opt can support the standard library using the command of `cargo rapx -opt -- -Z build-std --target x86_64-unknown-linux-gnu`.
The compiling of std starts from `core` then `alloc` and ends with `std`. This PR pre-checks whether the tcx has a context of `std` first and then controls the following checking entries. `vec` in `std` is actually loaded from `alloc::vec`. Thus it makes sense to find bound checks in std library.
> support bounds checking of no_std

- rapx/src/analysis/core/dataflow/debug.rs
- rapx/src/analysis/core/dataflow/graph.rs
- rapx/src/analysis/opt.rs
- rapx/src/analysis/opt/checking.rs
- rapx/src/analysis/opt/checking/bounds_checking.rs
- rapx/src/analysis/opt/checking/bounds_checking/bounds_extend.rs
- rapx/src/analysis/opt/checking/bounds_checking/bounds_len.rs
- rapx/src/analysis/opt/checking/encoding_checking.rs
- rapx/src/analysis/opt/checking/encoding_checking/array_encoding.rs
- rapx/src/analysis/opt/checking/encoding_checking/vec_encoding.rs
- rapx/src/analysis/opt/data_collection/unreserved_hash.rs
- rapx/src/analysis/opt/memory_cloning/hash_key_cloning.rs
- rapx/src/analysis/opt/memory_cloning/used_as_immutable.rs
- rapx/tests/others/todo/bounds_extend/Cargo.toml
- rapx/tests/others/todo/bounds_extend/src/lib.rs
- rapx/tests/others/todo/encoding_check/Cargo.toml
- rapx/tests/others/todo/encoding_check/src/lib.rs
- Add detection code of utf8 encoding (String created from Vec or Array)
- Fix bugs, including
- Infinite recursion caused by `rings` in the dataflow graph
- Debug error caused by marker nodes with `Use` NodeOp. Usually shows up in `_a[_b]=rvalue`. The left value creates a marker node and the assignment gives it `Use` op.
> Add encoding checks and fix bugs

- rapx/src/analysis/core/alias.rs
- rapx/src/analysis/core/alias/mop.rs
- rapx/src/analysis/safedrop/graph.rs
- rapx/src/analysis/senryx.rs
- rapx/src/analysis/senryx/dominated_chain.rs
- rapx/src/analysis/senryx/matcher.rs
- rapx/src/analysis/senryx/visitor.rs
- rapx/src/analysis/senryx/visitor_check.rs
- rapx/src/analysis/unsafety_isolation/data/std_sps.json
- rapx/src/analysis/unsafety_isolation/std_unsafety_isolation.rs
- rapx/src/analysis/utils/fn_info.rs
Previous alias results have redundant pairs like Alias(1,2) and Alias(2,1) for the indexes don't sort by value. 
This PR add an auxiliary method named `sort_alias_index` in `FnRetAlias` and update the SP names in std_sps.json.
> sort alias index & update sp json

- rapx/src/analysis.rs
- rapx/src/analysis/core/alias.rs
- rapx/src/analysis/core/alias/mop.rs
- rapx/src/analysis/core/alias/mop/alias.rs
- rapx/src/analysis/core/alias/mop/graph.rs
- rapx/src/analysis/safedrop.rs
- rapx/src/analysis/safedrop/alias.rs
- rapx/src/analysis/safedrop/safedrop.rs
- rapx/src/analysis/senryx.rs
- rapx/src/analysis/senryx/visitor.rs
- rapx/src/lib.rs
Summary of this PR:
- Introduces a unified Analysis and AliasAnalysis trait.
- Refactors the alias module:
- Renames key data structures to improve readability.
- AAFact and AAResult now only store common information shared across alias analysis results.
- Algorithm-specific data (e.g., left_need_drop, right_may_drop) has been moved to corresponding submodules.
- Updates downstream modules to ensure the codebase remains compilable.
> refactor: add uniform Analysis & AliasAnalysis trait and restructure alias module

- rapx/Cargo.lock
- rapx/src/analysis/core/dataflow.rs
- rapx/src/analysis/opt.rs
- rapx/src/lib.rs
Temporally define two funcs in DataFlowAnalysis
- fn has_flow_between(&self, def_id: DefId, local1: Local, local2: Local) -> bool;
- fn collect_equivalent_locals(&self, def_id: DefId, local: Local) -> HashSet<Local>;
> refactor dataflow analysis

- rapx/src/analysis/core/dataflow.rs
- rapx/src/analysis/core/dataflow/default.rs
- rapx/src/analysis/core/dataflow/graph.rs
1. Fix bug of param_return_deps in dataflow::Graph
2. Simplify the display string of DataFlowGraph
3. Keep the original implementation as Debug trait
> Modify the Display trait of DataFlowGraph

- rapx/src/analysis/unsafety_isolation/std_unsafety_isolation.rs
- rapx/src/def_id.rs
- rapx/src/lib.rs
- rapx/src/utils/mod.rs
> Fix:  replace `tcx.mir_keys()` by rustc_public API in `unsafety_isolation`

- rapx/Cargo.lock
- rapx/Cargo.toml
This fixes build failure on macos.  With the lower version of z3, I see
```
Compiling z3-sys v0.8.1
error: failed to run custom build command for `z3-sys v0.8.1`
Caused by:
process didn't exit successfully: `/var/folders/cf/bq94w26s3gv0twtfly7216rw0000gn/T/cargo-installECsnnf/release/build/z3-sys-fe197212dd03f2f4/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-env-changed=Z3_SYS_Z3_HEADER
cargo:rerun-if-changed=wrapper.h
cargo:rerun-if-env-changed=TARGET
cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-apple-darwin
cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_darwin
cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
--- stderr
wrapper.h:1:10: fatal error: 'z3.h' file not found
```
I can manually override …
> Upgrade z3 to 0.13.3

- README.md
- rapx/src/bin/cargo-rapx/help.rs
- rapx/src/bin/cargo-rapx/main.rs
This PR closes https://github.com/Artisan-Lab/RAPx/issues/183 by treating these arguments from RAPx instead of rustc.
> Fix: handle -v/--version/-h/--help arguments

- rapx/src/analysis/safedrop/graph.rs
- rapx/src/def_id.rs
- rapx/src/lib.rs
- rapx/tests/others/batch.sh
- rapx/tests/others/support/no_std/Cargo.toml
- rapx/tests/others/support/no_std/src/lib.rs
This PR fixes https://github.com/Artisan-Lab/RAPx/issues/190 by
* searching paths of intrinsics in extended paths: intrinsics in no_std crates will be matched against paths starting from core or alloc root
* handling dealloc for no_std crates without alloc via dealloc_opt
* each intrinsics DefId getter now has an optional variant: e.g. dealloc <=> dealloc_opt
* also adding a no_std testcase
> Fix: handle `#![no_std]` crates when retrieving intrinsics DefIds

- rapx/src/analysis/core/dataflow/graph.rs
- rapx/src/analysis/core/dataflow/mod.rs
Add two APIs for dataflow Graph:
- `collect_descending_locals`, collecting all locals in the downstream of the specific local
- `get_field_sequence`, get the field sequence of the specific marker node. e.g., foo.a.b.c (will get field numbers of foo, a, and b)
> feat: add APIs about descending and fields
